{"name": "Логин под существующим пользователем", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "@pytest.fixture(scope=\"function\")\n    def create_user():\n        payload = User.register_new_user()\n        login_data = payload.copy()\n        del login_data[\"name\"]\n        double_email = payload.copy()\n        del double_email[\"name\"]\n        del double_email[\"password\"]\n        response = requests.post(configuration.CREATE_USER_PATH, data=payload)\n>       token = response.json()[\"accessToken\"]\nE       KeyError: 'accessToken'\n\nconftest.py:16: KeyError"}, "start": 1721746393734, "stop": 1721746393734, "uuid": "0d6973af-cbf4-4f3e-818c-c9eab69f3bef", "historyId": "326dc5fc8558a1bc65b79e62c160b6f2", "testCaseId": "326dc5fc8558a1bc65b79e62c160b6f2", "fullName": "tests.test_login_user.TestLoginUser#test_success_login", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-5FK58OB"}, {"name": "thread", "value": "8076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}